# Welcome to Jekyll!
# 238619507
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "K925 Grayshott"
email: k925grayshott@gmail.com
name: "Stephane Rankin"
description: >- # this means to ignore newlines until "baseurl:"
  K925 dog walking & drop in service!
url : "https://www.k925grayshott.com"
twitter_username: username
github : [metadata]
github_username: K925grayshott
minimal_mistakes_skin: sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

  # mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


author:
  name   : "Stephane Rankin"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "For the love of dogs"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.k925grayshott.com"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/k925grayshott"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-official"
      url: "https://facebook.com/k925grayshott"
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/k925grayshott"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-official"
      url: "https://facebook.com/k925grayshott"
feed:
  disable: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sitemap: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sitemap: true
  - scope:
      path: 'assets/'
      values:
      sitemap: false      
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Reading Files
include: ["_pages"]
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - eventmachine.bat
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - /IFDROPDOWNNAV
  - /blogexamples
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# OCTOPRESS
# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: single

# Format titles with titlecase?
titlecase: true

google:
  search_engine_id       : xxxxxxxxxxxxx
  instant_search         : false # false (default), true

# SEO Related
google_site_verification : xxxxxxxxxxxxx
bing_site_verification   : xxxxxxxxxxxxx
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : k925grayshott
facebook:
  username               : k925grayshott
  app_id                 : 100648582798893
  publisher              :
og_image                 : "/assets/images/k925logo.png"

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type:  Organisation
  name:  K925Grayshott
  links:
    - "https://twitter.com/k925grayshott"
    - "https://www.facebook.com/k925grayshott/"
    - "https://instagram.com/k925grayshott"


# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : XXXX
    anonymize_ip         : false #true, false (default)
